### PR TITLE
Added Git Cop support.

### LINKED ISSUE #3: Add Git Cop
## Overview

Would there be interest in adding [Git Cop](https://github.com/bkuhlmann/git-cop) to this project as a CI linting tool?

By the way, I would highly recommend forcing a rebase workflow. You can enforce this via these [GitHub Settings](https://github.com/bkuhlmann/git-cop#github).

### PR DESCRIPTION
**Pull request by bkuhlmann**
## Overview

Will be used to ensure high quality Git commits are used on this project. See [Git Cop Documentation](https://github.com/bkuhlmann/git-cop) for further details.

## Details

- Resolves #3.
- See commits for details.

## Notes

@rylanb Should you not want the Netlify configuration checked into this repo, I could delete the `Added Netflify custom configuration.` commit in favor of you updating the build configuration within your Netlify settings of this app. Here's what you'd need to do instead:

netlify-settings

If you do that, I can drop the commit. ...or I can leave the commit. Either way is fine by me. :smile:

### CODE REVIEW

**Comment by rylanb** [comment]
I'm happy to do whatever is most simple based on your reco! Just let me know what you think is most easy from a contributor standpoint.

**Comment by bkuhlmann** [comment]
:bow: @rylanb, ok, it might be wise to allow the `netlify.toml` in the repo then. This'll make it more obvious how this project is built so other contributors can update as necessary as the project evolves.

**Comment by bkuhlmann** [comment]
@rylanb Should I rebase this onto `master`? You might want to approve these PRs so I know you are OK with me proceeding. :wink:

**Comment by rylanb** [comment]
Haha, you have to assign me so i know if its ready or not!

I updated to `gem --update system && bundle install && bundle exec rake code_quality` from `middleman build --verbose` does the

**Review by rylanb — APPROVED** [review]
Looks good to me, 

do I need `gem update --system && bundle install && bundle exec rake && middleman build` instead of the screenshotted command?

**Comment by bkuhlmann** [comment]
@rylanb Funny. There are so many different ways people can be notified on a PR but none of them are are the def facto for letting someone know you are done. 😅 

> do I need gem update --system && bundle install && bundle exec rake && middleman build instead of the screenshotted command?

↑ That is *mostly* an insurance policy to make sure the Docker container is up-to-date for build purposes. Overtime, we might be able to `bundle exec rake` only and call it good. Actually, I was thinking it might be wise to include `middleman build` as part of the `bundle exec rake` script (I can open up a different PR for that, though).

**Comment by rylanb** [comment]
Yeah, My preferred way is to assign it to the reviewer and add a label like 'Ready for Review' or 'Waiting for Review'. That way its super clear, imo, that its ready.

Netlify is updated to run `gem --update system && bundle install && bundle exec rake code_quality` 

So rebase onto master when ready.

**Comment by bkuhlmann** [comment]
:bow: @rylanb, good to know. I'll use that moving forward. I'll also rebase this onto `master` as soon as the build is green.

**Comment by bkuhlmann** [comment]
:information_source: Build failed because the Netlify user configuration is something like this:

``` 
gem --update && bundle install && bundle exec rake && middleman build
```

...but needs to be:

``` 
gem update --system && bundle install && bundle exec rake && middleman build
```

I restored my original commit. It's probably good, in the end, to expose this information in a transparent manner. :wink:

**Comment by rylanb** [comment]
Yeah that's fine with me. Should I take anything out of the Netlify build input?

**Comment by bkuhlmann** [comment]
I would probably clear out that input field. The TOML file takes precedence now so it won't hurt if you leave it as is but probably good to clear it out so you aren't confused at some point in the future. :wink:

**Comment by rylanb** [comment]
Cleared out!

**Pull request merged**
