### PR TITLE
Updated project dependencies

### PR DESCRIPTION
**Pull request by bkuhlmann**
## Overview

Updates the project to use latest Ruby and gem versions.

## Details

See commits for details.

## Notes

When testing locally, the changes look good. Will wait for the build process to confirm I didn't miss anything.

### CODE REVIEW

**Comment by bkuhlmann** [comment]
:information_source: Fascinating. The build passes on a fork project but fails when using the original project.

**Comment by rylanb** [comment]
Interesting. So do I have to clean up my commits trying to fix things or what?

**Comment by bkuhlmann** [comment]
@rylanb Yeah, that would help but would require a force push to `master`. That would make the current forks of this project to no longer be compatible, though. 😅 Maybe that's OK as it would only effect Elise? I added a new commit to temporarily disable Git Cop so the build goes green.

The build is green now so if you approve, I can rebase onto `master`. ...I can also dig into more more as to why Netlify has changed their build process.

**Review by rylanb — APPROVED** [review]
Great!

Teach me how to git cop, too! Then I can not break the build with my lazy commit msgs. 

I think its only Elise, myself, you. Happy to do whatever you think is best here.

**Comment by bkuhlmann** [comment]
@rylanb Ha, well, I'd recommend setting up Git Cop as a [local hook](https://github.com/bkuhlmann/git-cop#git-hooks). Otherwise, I just need to re-enable this project's `Rakefile` so it runs Git Cop as done for the Netlify build via `bundle exec rake`.

Longer term, I just need to figure out what broke with Netlify's build process so Git Cop doesn't check commits already on `master`.

**Pull request merged**
